// SPDX-License-Identifier: UNLICENSED
// Generated by forge-scriptgen.
pragma solidity ^0.8.23;

import "forge-std/Script.sol";
import "../src/CommentsAndStrings.sol";

contract CommentsAndStringsScript is Script {
    function run() public {
        uint256 deployerPrivateKey = 0xabc123;
        vm.startBroadcast(deployerPrivateKey);

        CommentsAndStrings instance = new CommentsAndStrings("0xDeAdBeEf", "hello");
        vm.stopBroadcast();
    }
}
