// SPDX-License-Identifier: UNLICENSED
// Generated by forge-scriptgen.
pragma solidity ^0.8.24;

import "forge-std/Script.sol";
import "../src/nested/ComplexDeployment.sol";

contract ComplexDeploymentScript is Script {
    function run() public {
        uint256 deployerPrivateKey = 0xabc123;
        vm.startBroadcast(deployerPrivateKey);

        ComplexDeployment instance = new ComplexDeployment(Config({owner: msg.sender, limits: [1, 2, 3]}), callback, "primary", hex"1234");
        vm.stopBroadcast();
    }
}
